import { useMemo } from "react";
import { useNavigate } from "react-router-dom";
import StatCard from "../components/StatCard";
import IncidentTable from "../components/IncidentTable";
import CpuChart from "../components/CpuChart";
import { Badge } from "../components/Badge";
import { Icon } from "../components/Icons";

export default function Dashboard({ incidents }) {
  const navigate = useNavigate();
  const active = incidents.filter((i) => i.status !== "RESOLVED");
  const high = incidents.filter((i) => i.severity === "HIGH" || i.severity === "CRITICAL");
  const current = incidents[0];
  const rawCurrentCpu = current?.metrics?.cpu_utilization?.latest_cpu;
  const avg = Number.isFinite(Number(rawCurrentCpu))
    ? (Number(rawCurrentCpu) <= 1 ? Number(rawCurrentCpu) * 100 : Number(rawCurrentCpu))
    : null;

  const health = useMemo(() => [
    ["CloudWatch", "Connected"],
    ["EventBridge", "Configured"],
    ["Lambda Agent", "Configured"],
    ["Bedrock RAG", "Available"],
    ["DynamoDB", "Connected"]
  ], []);

  return (
    <>
      <div className="page-header">
        <div><div className="eyebrow">OVERVIEW</div><h1>Cloud Operations Overview</h1><p>Real-time infrastructure monitoring and AI-powered incident investigation.</p></div>
        <button className="primary-btn" onClick={() => navigate("/incidents")}><Icon name="alert" size={16}/> View incidents</button>
      </div>

      <div className="stats-grid">
        <StatCard icon="alert" label="ACTIVE INCIDENTS" value={active.length} meta="Needs attention" tone="red"/>
        <StatCard icon="alert" label="HIGH SEVERITY" value={high.length} meta="Requires investigation" tone="amber"/>
        <StatCard icon="server" label="MONITORED INSTANCES" value={new Set(incidents.map((i) => i.infrastructure?.instance_id).filter(Boolean)).size} meta="EC2 infrastructure" tone="blue"/>
        <StatCard icon="brain" label="AI ANALYSES" value={incidents.length} meta="Generated by AegisOps" tone="purple"/>
        <StatCard icon="book" label="RAG RETRIEVALS" value={incidents.reduce((n, i) => n + (i.runbook?.retrieved_chunks?.length || 0), 0)} meta="Knowledge base active" tone="cyan"/>
      </div>

      <div className="content-grid two-thirds">
        <section className="panel">
          <div className="section-head compact"><div><div className="section-kicker">OPERATIONS</div><h2>Active Incidents</h2></div><Badge tone="red">{active.length} ACTIVE</Badge></div>
          <IncidentTable incidents={active}/>
        </section>

        <section className="panel cpu-panel">
          <div className="section-head compact"><div><div className="section-kicker">OBSERVABILITY</div><h2>CPU Monitoring</h2></div><Badge tone="green">BELOW THRESHOLD</Badge></div>
          <div className="cpu-current"><div><span>Current CPU</span><strong>{avg === null ? "N/A" : avg.toFixed(0)}<small>{avg === null ? "" : "%"}</small></strong></div><div className="cpu-threshold"><span>Alarm threshold</span><strong>70%</strong></div></div>
          <CpuChart values={current?.metrics?.cpu_utilization?.values || []} threshold={70}/>
          <div className="cpu-foot"><span><i className="legend-line blue"></i> CPU utilization</span><span><i className="legend-line red"></i> Alarm threshold</span></div>
        </section>
      </div>

      <div className="content-grid two-thirds">
        <section className="panel">
          <div className="section-head compact"><div><div className="section-kicker">INFRASTRUCTURE</div><h2>Integration Health</h2></div></div>
          <div className="health-grid">{health.map(([name, status]) => <div className="health-item" key={name}><span className="health-icon"><Icon name="check" size={15}/></span><div><strong>{name}</strong><small>{status}</small></div><span className="status-dot green"/></div>)}</div>
        </section>

        <section className="panel">
          <div className="section-head compact"><div><div className="section-kicker">RECENT ACTIVITY</div><h2>Latest Incident</h2></div><button className="text-btn" onClick={() => navigate("/incidents")}>View all <Icon name="arrow" size={14}/></button></div>
          {current && <div className="latest-card" onClick={() => navigate(`/incidents/${current.incident_id}`)}>
            <div className="latest-top"><span className="incident-dot red"></span><div><strong>{current.incident_id}</strong><small>{current.alarm_name}</small></div><Badge tone="red">{current.severity}</Badge></div>
            <div className="latest-grid"><div><span>Status</span><strong>{current.status}</strong></div><div><span>Instance</span><strong className="mono">{current.infrastructure.instance_id}</strong></div><div><span>CPU</span><strong>{current.metrics?.cpu_utilization?.latest_cpu == null ? "N/A" : `${(current.metrics.cpu_utilization.latest_cpu <= 1 ? current.metrics.cpu_utilization.latest_cpu * 100 : current.metrics.cpu_utilization.latest_cpu).toFixed(0)}%`}</strong></div></div>
          </div>}
        </section>
      </div>
    </>
  );
}